### ISSUE TITLE
Compile/link error

### ISSUE THREAD

**Issue by pjalocha** [triq-org/tx_tools#3] opened 2022-04-05 19:57 UTC
It can not build the tx_sdr tool, I tried on two different systems, the error is included below. could you maybe help ?

Thank you.

[100%] Linking C executable tx_sdr
/usr/bin/ld: libcommon.a(sdr_soapy.c.o): in function `soapy_enum_devices':
sdr_soapy.c:(.text+0xc3f): undefined reference to `SoapySDRDevice_make_list'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/tx_sdr.dir/build.make:86: tx_sdr] Error 1
make[1]: *** [CMakeFiles/Makefile2:1061: CMakeFiles/tx_sdr.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

**Comment by zuckschwerdt** [comment] 2022-04-06 03:35
Looks like compiling went fine (the headers are there) but linking failed -- the libs are not installed?

Can you give some info on your system (distro, arch, compiler) and which version of SoapySDR is installed?

And try `cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_BUILD_TYPE=Debug .. && make` to show the failed linking command.

**Comment by zuckschwerdt** [comment] 2022-04-10 10:08
Let me know if you need further help. Closing not-reproducible.

**Closed as completed by zuckschwerdt** 2022-04-10 10:08 UTC
